---
# tasks file for nginx


- name: Install the latest version of "{{ service_name }}" on "{{ env_name }}"
  ansible.builtin.yum:
    name: "{{ service_name }}"
    state: latest

- name: Start service "{{ service_name }}", if not started on "{{ env_name }}"
  ansible.builtin.service:
    name: "{{ service_name }}"
    state: started

